version: "3.8"

services:
  siteship-workflows:
    image: ghcr.io/samsha1/siteship-workflows:${SOFTWARE_VERSION_TAG}
    container_name: siteship-workflows
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    env_file: .env
    depends_on:
      - postgres
      - redis
    environment:
      # Airflow Core Config
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${ADMIN_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:${ADMIN_PASSWORD}@postgres:5432/airflow
      AIRFLOW__VARIABLES__SUPABASE_URL: ${SUPABASE_URL}
      AIRFLOW__VARIABLES__SUPABASE_KEY: ${SUPABASE_KEY}
      AIRFLOW__VARIABLES__GHCR_USERNAME: ${GHCR_USERNAME}
      AIRFLOW__VARIABLES__GHCR_PAT: ${GHCR_PAT}
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
      AIRFLOW__VARIABLES__GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      AIRFLOW__VARIABLES__SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      AIRFLOW__VARIABLES__GEMINI_API_KEY: ${GEMINI_API_KEY}
      AIRFLOW__VARIABLES__EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      AIRFLOW__VARIABLES__COMPLETION_MODEL: ${COMPLETION_MODEL}
      AIRFLOW__VARIABLES__OPENAI_API_KEY: ${OPENAI_API_KEY}
      AIRFLOW__VARIABLES__TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      AIRFLOW__VARIABLES__VERCEL_ACCESS_TOKEN: ${VERCEL_ACCESS_TOKEN}
      AIRFLOW__VARIABLES__NOTIFICATION_PHONE: ${NOTIFICATION_PHONE}
      AIRFLOW__VARIABLES__TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      AIRFLOW__VARIABLES__TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      AIRFLOW__VARIABLES__TWILIO_SANDBOX_PHONE_NUM: ${TWILIO_SANDBOX_PHONE_NUM}
      AIRFLOW__VARIABLES__TWILIO_PHONE_NUM: ${TWILIO_PHONE_NUM}
      AIRFLOW__VARIABLES__VERCEL_GITHUB_REPO: ${VERCEL_GITHUB_REPO}
      AIRFLOW__VARIABLES__GITHUB_REPO: ${GITHUB_REPO}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}

      # Webserver Auth
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: ${ADMIN_PASSWORD}
      _AIRFLOW_WWW_USER_EMAIL: ${ADMIN_EMAIL}
      _AIRFLOW_WWW_USER_FIRSTNAME: Air
      _AIRFLOW_WWW_USER_LASTNAME: Flow

      # Other useful vars
      AIRFLOW__CORE__LOAD_EXAMPLES: "true"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      # Optional for Elestio deployment
      TZ: UTC
      AIRFLOW_HOME: /opt/airflow

    ports:
      - 172.17.0.1:8080:8080

    volumes:
    #   - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

    command: >
      bash -c '
        airflow db migrate &&
        airflow users create \
            --username admin \
            --firstname ${_AIRFLOW_WWW_USER_FIRSTNAME} \
            --lastname ${_AIRFLOW_WWW_USER_LASTNAME} \
            --role Admin \
            --email ${_AIRFLOW_WWW_USER_EMAIL} \
            --password ${_AIRFLOW_WWW_USER_PASSWORD} || true; 
        airflow api-server
      '
    networks:
      - airflow

  scheduler:
    image: ghcr.io/samsha1/siteship-workflows:${SOFTWARE_VERSION_TAG}
    container_name: siteship-scheduler
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${ADMIN_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:${ADMIN_PASSWORD}@postgres:5432/airflow
      AIRFLOW__VARIABLES__SUPABASE_URL: ${SUPABASE_URL}
      AIRFLOW__VARIABLES__SUPABASE_KEY: ${SUPABASE_KEY}
      AIRFLOW__VARIABLES__GHCR_USERNAME: ${GHCR_USERNAME}
      AIRFLOW__VARIABLES__GHCR_PAT: ${GHCR_PAT}
      AIRFLOW__VARIABLES__GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      AIRFLOW__VARIABLES__SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      AIRFLOW__VARIABLES__GEMINI_API_KEY: ${GEMINI_API_KEY}
      AIRFLOW__VARIABLES__EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      AIRFLOW__VARIABLES__COMPLETION_MODEL: ${COMPLETION_MODEL}
      AIRFLOW__VARIABLES__OPENAI_API_KEY: ${OPENAI_API_KEY}
      AIRFLOW__VARIABLES__TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      AIRFLOW__VARIABLES__VERCEL_ACCESS_TOKEN: ${VERCEL_ACCESS_TOKEN}
      AIRFLOW__VARIABLES__NOTIFICATION_PHONE: ${NOTIFICATION_PHONE}
      AIRFLOW__VARIABLES__TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      AIRFLOW__VARIABLES__TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      AIRFLOW__VARIABLES__TWILIO_SANDBOX_PHONE_NUM: ${TWILIO_SANDBOX_PHONE_NUM}
      AIRFLOW__VARIABLES__TWILIO_PHONE_NUM: ${TWILIO_PHONE_NUM}
      AIRFLOW__VARIABLES__VERCEL_GITHUB_REPO: ${VERCEL_GITHUB_REPO}
      AIRFLOW__VARIABLES__GITHUB_REPO: ${GITHUB_REPO}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW_HOME: /opt/airflow
    volumes:
    #   - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    #   - ./plugins:/opt/airflow/plugins
    command: >
        bash -c "
            airflow db migrate && airflow scheduler
        "
    networks:
      - airflow
  worker:
    image: ghcr.io/samsha1/siteship-workflows:${SOFTWARE_VERSION_TAG}
    container_name: siteship-worker
    restart: always
    env_file: .env
    depends_on:
      - redis
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${ADMIN_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:${ADMIN_PASSWORD}@postgres:5432/airflow
      AIRFLOW__VARIABLES__SUPABASE_URL: ${SUPABASE_URL}
      AIRFLOW__VARIABLES__SUPABASE_KEY: ${SUPABASE_KEY}
      AIRFLOW__VARIABLES__GHCR_USERNAME: ${GHCR_USERNAME}
      DUMB_INIT_SETSID: "0"
      AIRFLOW__VARIABLES__GHCR_PAT: ${GHCR_PAT}
      AIRFLOW__VARIABLES__GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      AIRFLOW__VARIABLES__SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      AIRFLOW__VARIABLES__GEMINI_API_KEY: ${GEMINI_API_KEY}
      AIRFLOW__VARIABLES__EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      AIRFLOW__VARIABLES__COMPLETION_MODEL: ${COMPLETION_MODEL}
      AIRFLOW__VARIABLES__OPENAI_API_KEY: ${OPENAI_API_KEY}
      AIRFLOW__VARIABLES__TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      AIRFLOW__VARIABLES__VERCEL_ACCESS_TOKEN: ${VERCEL_ACCESS_TOKEN}
      AIRFLOW__VARIABLES__NOTIFICATION_PHONE: ${NOTIFICATION_PHONE}
      AIRFLOW__VARIABLES__TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      AIRFLOW__VARIABLES__TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      AIRFLOW__VARIABLES__TWILIO_SANDBOX_PHONE_NUM: ${TWILIO_SANDBOX_PHONE_NUM}
      AIRFLOW__VARIABLES__TWILIO_PHONE_NUM: ${TWILIO_PHONE_NUM}
      AIRFLOW__VARIABLES__VERCEL_GITHUB_REPO: ${VERCEL_GITHUB_REPO}
      AIRFLOW__VARIABLES__GITHUB_REPO: ${GITHUB_REPO}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW_HOME: /opt/airflow

    volumes:
      - ./logs:/opt/airflow/logs

    command: >
      bash -c "airflow celery worker"
    deploy:
        resources:
            limits:
              cpus: '0.5'
              memory: 512M
    networks:
      - airflow

  redis:
    image: redis:7-alpine
    container_name: siteship-redis
    restart: always
    expose:
      - "6379"
    ports:
      - 172.17.0.1:64408:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - airflow

  postgres:
    image: postgres:17
    container_name: siteship-postgres
    restart: always
    ports:
      - 172.17.0.1:30782:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  postgres_data:
  airflow_logs:
networks:
  airflow:
    driver: bridge